language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - .npm
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: yarn test
    - stage: deploy
      name: "Deploy to GH Pages"
      if: branch = v2
      script: yarn deploy